// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	DeleteOrder(ctx context.Context, id uuid.UUID) error
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	// Example for a more complex update if needed, e.g., updating multiple fields
	UpdateOrderDetails(ctx context.Context, arg UpdateOrderDetailsParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
