apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.appName" . }}-deployment
  labels:
    app: {{ include "helm-chart.appName" . }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm-chart.appName" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-chart.appName" . }}
    spec:
      nodeSelector:
        node_type: {{ .Values.deployment.spec.nodeSelector.node_type }}
        node_app: {{ .Values.deployment.spec.nodeSelector.node_app }}
      containers:
      - name: {{ include "helm-chart.appName" . }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ .Values.deployment.containers.resources.requests.memory }}
            cpu: {{ .Values.deployment.containers.resources.requests.cpu }}
            # ephemeral-storage: {{ .Values.deployment.containers.resources.requests.ephemeral_storage }}
          limits:
            memory: {{ .Values.deployment.containers.resources.limits.memory }}
            cpu: {{ .Values.deployment.containers.resources.limits.cpu }}
            # ephemeral-storage: {{ .Values.deployment.containers.resources.limits.ephemeral_storage }}

